import { Model3D } from '../types/model';

export const models: Model3D[] = [
  {
    id: '1',
    name: 'Metallic Cube',
    description: 'A metallic cube with high reflectivity, showcasing PBR materials with low roughness for a polished metal appearance.',
    type: 'box',
    color: '#4a90e2',
    metalness: 0.9,
    roughness: 0.1,
    wireframe: false,
  },
  {
    id: '2',
    name: 'Glossy Sphere',
    description: 'A smooth sphere with gradient lighting, demonstrating diffuse reflection and ambient occlusion effects.',
    type: 'sphere',
    color: '#e94b3c',
    metalness: 0.3,
    roughness: 0.2,
    wireframe: false,
  },
  {
    id: '3',
    name: 'Wireframe Pyramid',
    description: 'A geometric pyramid rendered in wireframe mode, perfect for technical visualizations and geometric studies.',
    type: 'pyramid',
    color: '#50c878',
    metalness: 0,
    roughness: 0.8,
    wireframe: true,
  },
  {
    id: '4',
    name: 'Golden Torus',
    description: 'A golden torus with high metalness, showcasing complex geometry and realistic metal material properties.',
    type: 'torus',
    color: '#ffd700',
    metalness: 1.0,
    roughness: 0.15,
    wireframe: false,
  },
  {
    id: '5',
    name: 'Matte Cone',
    description: 'A matte-finished cone with high roughness, demonstrating non-reflective surface properties.',
    type: 'cone',
    color: '#9b59b6',
    metalness: 0,
    roughness: 0.9,
    wireframe: false,
  },
];
